// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        (unknown)
// source: proto/gosnapraid/gosnapraid.proto

package gosnapraidpb

import (
	_ "github.com/planetscale/vtprotobuf/vtproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HashType int32

const (
	HashType_HASH_UNKNOWN  HashType = 0
	HashType_HASH_XXHASH64 HashType = 1
	HashType_HASH_SHA256   HashType = 2
)

// Enum value maps for HashType.
var (
	HashType_name = map[int32]string{
		0: "HASH_UNKNOWN",
		1: "HASH_XXHASH64",
		2: "HASH_SHA256",
	}
	HashType_value = map[string]int32{
		"HASH_UNKNOWN":  0,
		"HASH_XXHASH64": 1,
		"HASH_SHA256":   2,
	}
)

func (x HashType) Enum() *HashType {
	p := new(HashType)
	*p = x
	return p
}

func (x HashType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HashType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gosnapraid_gosnapraid_proto_enumTypes[0].Descriptor()
}

func (HashType) Type() protoreflect.EnumType {
	return &file_proto_gosnapraid_gosnapraid_proto_enumTypes[0]
}

func (x HashType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HashType.Descriptor instead.
func (HashType) EnumDescriptor() ([]byte, []int) {
	return file_proto_gosnapraid_gosnapraid_proto_rawDescGZIP(), []int{0}
}

type SnapshotHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Snapshot version
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Snapshot creation timestamp in unix nanoseconds
	Timestamp uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *SnapshotHeader) Reset() {
	*x = SnapshotHeader{}
	mi := &file_proto_gosnapraid_gosnapraid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotHeader) ProtoMessage() {}

func (x *SnapshotHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gosnapraid_gosnapraid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotHeader.ProtoReflect.Descriptor instead.
func (*SnapshotHeader) Descriptor() ([]byte, []int) {
	return file_proto_gosnapraid_gosnapraid_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotHeader) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SnapshotHeader) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SnapshotNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// File path, primary key
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Basic file metadata for fast-diffing
	Size  uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mtime uint64 `protobuf:"varint,3,opt,name=mtime,proto3" json:"mtime,omitempty"` // last modified time in unix nanoseconds
	Mode  uint32 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	// Hash fields for authoritative change detection & integrity checking
	Hashtype HashType `protobuf:"varint,5,opt,name=hashtype,proto3,enum=gosnapraid.HashType" json:"hashtype,omitempty"`
	Hashhi   uint64   `protobuf:"fixed64,6,opt,name=hashhi,proto3" json:"hashhi,omitempty"`
	Hashlo   uint64   `protobuf:"fixed64,7,opt,name=hashlo,proto3" json:"hashlo,omitempty"`
	// Fields for slice range tracking
	SliceRangeStarts []uint32 `protobuf:"varint,8,rep,packed,name=slice_range_starts,json=sliceRangeStarts,proto3" json:"slice_range_starts,omitempty"`
	SliceRangeEnds   []uint32 `protobuf:"varint,9,rep,packed,name=slice_range_ends,json=sliceRangeEnds,proto3" json:"slice_range_ends,omitempty"`
}

func (x *SnapshotNode) Reset() {
	*x = SnapshotNode{}
	mi := &file_proto_gosnapraid_gosnapraid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotNode) ProtoMessage() {}

func (x *SnapshotNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gosnapraid_gosnapraid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotNode.ProtoReflect.Descriptor instead.
func (*SnapshotNode) Descriptor() ([]byte, []int) {
	return file_proto_gosnapraid_gosnapraid_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotNode) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SnapshotNode) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SnapshotNode) GetMtime() uint64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *SnapshotNode) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *SnapshotNode) GetHashtype() HashType {
	if x != nil {
		return x.Hashtype
	}
	return HashType_HASH_UNKNOWN
}

func (x *SnapshotNode) GetHashhi() uint64 {
	if x != nil {
		return x.Hashhi
	}
	return 0
}

func (x *SnapshotNode) GetHashlo() uint64 {
	if x != nil {
		return x.Hashlo
	}
	return 0
}

func (x *SnapshotNode) GetSliceRangeStarts() []uint32 {
	if x != nil {
		return x.SliceRangeStarts
	}
	return nil
}

func (x *SnapshotNode) GetSliceRangeEnds() []uint32 {
	if x != nil {
		return x.SliceRangeEnds
	}
	return nil
}

var File_proto_gosnapraid_gosnapraid_proto protoreflect.FileDescriptor

var file_proto_gosnapraid_gosnapraid_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x73, 0x6e, 0x61, 0x70, 0x72, 0x61,
	0x69, 0x64, 0x2f, 0x67, 0x6f, 0x73, 0x6e, 0x61, 0x70, 0x72, 0x61, 0x69, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x6f, 0x73, 0x6e, 0x61, 0x70, 0x72, 0x61, 0x69, 0x64, 0x1a,
	0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65,
	0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x0e, 0x53, 0x6e, 0x61, 0x70,
	0x73, 0x68, 0x6f, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0xa0, 0x02, 0x0a, 0x0c, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x4e,
	0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6d, 0x74, 0x69, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x68, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x73, 0x6e, 0x61, 0x70,
	0x72, 0x61, 0x69, 0x64, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x68,
	0x61, 0x73, 0x68, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x61, 0x73, 0x68, 0x68,
	0x69, 0x18, 0x06, 0x20, 0x01, 0x28, 0x06, 0x52, 0x06, 0x68, 0x61, 0x73, 0x68, 0x68, 0x69, 0x12,
	0x16, 0x0a, 0x06, 0x68, 0x61, 0x73, 0x68, 0x6c, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x06, 0x52,
	0x06, 0x68, 0x61, 0x73, 0x68, 0x6c, 0x6f, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x6c, 0x69, 0x63, 0x65,
	0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x73, 0x18, 0x08, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x10, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x73, 0x12, 0x28, 0x0a, 0x10, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x5f, 0x72,
	0x61, 0x6e, 0x67, 0x65, 0x5f, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x0e, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x6e, 0x64, 0x73, 0x3a,
	0x04, 0xa8, 0xa6, 0x1f, 0x01, 0x2a, 0x40, 0x0a, 0x08, 0x48, 0x61, 0x73, 0x68, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x10, 0x0a, 0x0c, 0x48, 0x41, 0x53, 0x48, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x48, 0x41, 0x53, 0x48, 0x5f, 0x58, 0x58, 0x48, 0x41,
	0x53, 0x48, 0x36, 0x34, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x48, 0x41, 0x53, 0x48, 0x5f, 0x53,
	0x48, 0x41, 0x32, 0x35, 0x36, 0x10, 0x02, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x61, 0x72, 0x65, 0x74, 0x68, 0x67, 0x65, 0x6f, 0x72,
	0x67, 0x65, 0x2f, 0x67, 0x6f, 0x73, 0x6e, 0x61, 0x70, 0x72, 0x61, 0x69, 0x64, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x73, 0x6e, 0x61, 0x70, 0x72, 0x61, 0x69, 0x64, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_gosnapraid_gosnapraid_proto_rawDescOnce sync.Once
	file_proto_gosnapraid_gosnapraid_proto_rawDescData = file_proto_gosnapraid_gosnapraid_proto_rawDesc
)

func file_proto_gosnapraid_gosnapraid_proto_rawDescGZIP() []byte {
	file_proto_gosnapraid_gosnapraid_proto_rawDescOnce.Do(func() {
		file_proto_gosnapraid_gosnapraid_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_gosnapraid_gosnapraid_proto_rawDescData)
	})
	return file_proto_gosnapraid_gosnapraid_proto_rawDescData
}

var file_proto_gosnapraid_gosnapraid_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_gosnapraid_gosnapraid_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_gosnapraid_gosnapraid_proto_goTypes = []any{
	(HashType)(0),          // 0: gosnapraid.HashType
	(*SnapshotHeader)(nil), // 1: gosnapraid.SnapshotHeader
	(*SnapshotNode)(nil),   // 2: gosnapraid.SnapshotNode
}
var file_proto_gosnapraid_gosnapraid_proto_depIdxs = []int32{
	0, // 0: gosnapraid.SnapshotNode.hashtype:type_name -> gosnapraid.HashType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_gosnapraid_gosnapraid_proto_init() }
func file_proto_gosnapraid_gosnapraid_proto_init() {
	if File_proto_gosnapraid_gosnapraid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_gosnapraid_gosnapraid_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_gosnapraid_gosnapraid_proto_goTypes,
		DependencyIndexes: file_proto_gosnapraid_gosnapraid_proto_depIdxs,
		EnumInfos:         file_proto_gosnapraid_gosnapraid_proto_enumTypes,
		MessageInfos:      file_proto_gosnapraid_gosnapraid_proto_msgTypes,
	}.Build()
	File_proto_gosnapraid_gosnapraid_proto = out.File
	file_proto_gosnapraid_gosnapraid_proto_rawDesc = nil
	file_proto_gosnapraid_gosnapraid_proto_goTypes = nil
	file_proto_gosnapraid_gosnapraid_proto_depIdxs = nil
}
